# Config file for Stage 5 - Wave Characterization

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage05_wave_characterization'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'LENS'

# Name of the output file
STAGE_OUTPUT: 'measures.csv'

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: 'None'  # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# Measures to compute
# 'label_planar', 'velocity_planar', 'direction', 'velocity_point'
MEASURES: [velocity_point]

# Label Planar
##############
ALIGNMENT_THRESHOLD: 0.9
