# Config file for Stage 1 - Data Entry

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage01_data_entry'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'LENS'

# Name of stage output file.
STAGE_OUTPUT: "data.nix"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: nix

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/

DATA_SETS:
     LENS_170110_mouse2_t1: /Users/pino/Desktop/wavescalephant-master/Dataset/Ketamine/ketamine_25Hz/170110/mouse2/deep/t1


CURATION_SCRIPT: 'curate_LENS_data.py'

# pixel size
SPATIAL_SCALE: 0.05  # mm

SAMPLING_RATE: 25  # Hz

# time slice in s
# if None, the entire recording is used
T_START: None
T_STOP: None

# Metadata
ANNOTATIONS:
    experimental_lab: 'Pavone lab - Florence'

ARRAY_ANNOTATIONS: 'None'

KWARGS: 'None'

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [4040, 5050, 6060]  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: 'png'
