name: cobrawap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >= 3.8
  - pip >= 19.3.1
  - jinja2 >= 2.10.3
  - pygments >= 2.4.2
  - pygraphviz >= 1.5
  - snakemake >= 7.10.0 , < 8.0.0
  - h5py
  - shapely
  - ruamel.yaml == 0.17.32
  - pip:
    - elephant >= 1.0.0
    - neo >= 0.10.2
    - nixio >= 1.5.3
    - pillow >= 7.0.0
    - pandas >= 1.2.0
    - pulp < 2.8
    - scikit-learn >= 1.1.0
    - scikit-image >= 0.20.0
    - scipy >= 1.7.3
    - matplotlib >= 3.5.1
    - seaborn
    - networkx
    - sphinx>=3.3.0
    - sphinx-tabs>=1.3.0
    - sphinx-argparse>=0.3.2
